# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: default
  labels:
    app: azdevops-agent
spec:
  replicas: 1  # Keep one agent running at all times
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: systempool # Only run on system node pool
      containers:
      - name: azdevops-agent
        image: docker.io/siavashhub/azure-devops-agent:latest
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"        
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/<organization>" # Replace <organization> with your Azure DevOps organization name
          - name: AZP_POOL
            value: "aks-selfhosted"
          - name: AZP_AGENT_NAME
            value: "lightweight-agent-disable"            
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN