# secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  # Don't push replaced encoded data to the repo; use Key Vault or another secure method to manage secrets.
  AZP_TOKEN: <base64-encoded-ADOPAT>  # Replace with your base64 encoded PAT