apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
---

apiVersion: v1
kind: Service
metadata:
  name: backend-1
  namespace: sample-app
spec:
  selector:
    app: backend-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-1
  namespace: sample-app
  labels:
    app: backend-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-1
  template:
    metadata:
      labels:
        app: backend-1
    spec:
      containers:
      - name: backend-1
        image: docker.io/siavashhub/fastapi-hello:latest
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "10"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_NAME
          value: "App1"                 
        resources:
          requests:
            cpu: 10m
            memory: "0.5Gi"
          limits:
            cpu: "100m"
            memory: "1Gi"               
---
apiVersion: v1
kind: Service
metadata:
  name: backend-2
  namespace: sample-app
spec:
  selector:
    app: backend-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-2
  namespace: sample-app
  labels:
    app: backend-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-2
  template:
    metadata:
      labels:
        app: backend-2
    spec:
      containers:
      - name: backend-2
        image: docker.io/siavashhub/fastapi-hello:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_NAME
          value: "App2"                 
        resources:
          requests:
            cpu: 10m
            memory: "0.5Gi"
          limits:
            cpu: "100m"
            memory: "1Gi"   